# Generated by Django 5.2.3 on 2025-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('contact', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('patientAge', models.PositiveIntegerField(blank=True, null=True)),
                ('unitsNeeded', models.PositiveIntegerField()),
                ('urgency', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('requiredBy', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('requestedAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('lastDonated', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('availability', models.CharField(default='Available', max_length=20)),
                ('donationCount', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('emergencyContact', models.CharField(blank=True, max_length=15, null=True)),
                ('medicalHistory', models.TextField(blank=True, null=True)),
                ('preferredTime', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registeredSince', models.DateField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('bloodPressure', models.CharField(blank=True, max_length=20, null=True)),
                ('lastCheckup', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
